# Generated by Django 3.0.7 on 2020-06-13 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wheatCanada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('fdc', models.IntegerField()),
                ('dc', models.IntegerField()),
                ('fc', models.IntegerField()),
                ('ah', models.IntegerField()),
            ],
        ),
    ]
